version: "3.4"

services:
  facesapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "6000:80"
      - "50001:50001"

  facesapi-dapr:
    command:
      [
        "./daprd",
        "-app-id",
        "facesapi",
        "-app-port",
        "80",
        "-components-path",
        "/components",
      ]
    volumes:
      - "./dapr/components/:/components"

  ordersapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - OrdersContext=Server=sqldata;Database=OrdersDb;User Id=sa;Password=Pass@word
      - FacesAPIUrl=http://facesapi
    ports:
      - "5000:80"
      - "50002:50001"

  ordersapi-dapr:
    command:
      [
        "./daprd",
        "-app-id",
        "ordersapi",
        "-app-port",
        "80",
        "-placement-host-address",
        "dapr-placement:50000",
        "-components-path",
        "/components",
      ]
    volumes:
      - "./dapr/components/:/components"

  faceswebapp:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - OrdersAPIUrl=http://facesapigw
    ports:
      - "7000:80"

  notificationapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  notificationapi-dapr:
    command:
      [
        "./daprd",
        "-app-id",
        "notificationapi",
        "-app-port",
        "80",
        "-placement-host-address",
        "dapr-placement:50000",
        "-components-path",
        "/components",
      ]
    volumes:
      - "./dapr/components/:/components"

  facesapigw:
    volumes:
      - ./src/api/ApiGateways/Envoy:/etc/envoy
    ports:
      - "5202:80"
      - "15202:8001"
      - "50003:50001"

  facesapigw-dapr:
    command:
      [
        "./daprd",
        "-app-id",
        "facesapigw",
        "-app-port",
        "80",
        "-components-path",
        "/components",
      ]
    volumes:
      - "./dapr/components/:/components"

  sqldata:
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "1445:1433"

  redis:
    image: redis:alpine
    ports:
      - "5379:6379"

  dapr-placement:
    command: ["./placement", "-port", "50000", "-log-level", "debug"]
    ports:
      - "50000:50000"