kind: ConfigMap
apiVersion: v1
metadata:
  name: faceswebapp-cm
  namespace: faces
  labels:
    app: facesapp
    service: faceswebapp
data:
  ASPNETCORE_ENVIRONMENT: Development
  OrdersAPIUrl: http://facesapigw

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: faceswebapp
  namespace: faces
  labels:
    app: facesapp
    service: faceswebapp
spec:
  replicas: 1
  selector:
    matchLabels:
      service: faceswebapp
  template:
    metadata:
      labels:
        app: facesapp
        service: faceswebapp
    spec:
      containers:
        - name: faceswebapp
          image: faceswebapp:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          envFrom:
            - configMapRef:
                name: faceswebapp-cm

---

kind: Service
apiVersion: v1
metadata:
  name: faceswebapp-service
  namespace: faces
  labels:
    app: facesapp
    service: faceswebapp
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30011
      protocol: TCP
      name: http
  selector:
    service: faceswebapp
