kind: ConfigMap
apiVersion: v1
metadata:
  name: notificationapi-cm
  namespace: faces
  labels:
    app: facesapp
    service: notificationapi
data:
  ASPNETCORE_ENVIRONMENT: Development

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: notificationapi
  namespace: faces
  labels:
    app: facesapp
    service: notificationapi
spec:
  replicas: 1
  selector:
    matchLabels:
      service: notificationapi
  template:
    metadata:
      labels:
        app: facesapp
        service: notificationapi
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "notificationapi"
        dapr.io/app-port: "80"
    spec:
      containers:
        - name: notificationapi
          image: notificationapi:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          envFrom:
            - configMapRef:
                name: notificationapi-cm

---

kind: Service
apiVersion: v1
metadata:
  name: notificationapi-service
  namespace: faces
  labels:
    app: facesapp
    service: notificationapi
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30010
      protocol: TCP
      name: http
  selector:
    service: notificationapi
