kind: ConfigMap
apiVersion: v1
metadata:
  name: ordersapi-cm
  namespace: faces
  labels:
    app: facesapp
    service: ordersapi
data:
  ASPNETCORE_ENVIRONMENT: Development
  OrdersContext: Server=sqldata;Database=OrdersDb;User Id=sa;Password=Pass@word
  FacesAPIUrl: http://facesapi-service

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: ordersapi
  namespace: faces
  labels:
    app: facesapp
    service: ordersapi
spec:
  replicas: 1
  selector:
    matchLabels:
      service: ordersapi
  template:
    metadata:
      labels:
        app: facesapp
        service: ordersapi
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "ordersapi"
        dapr.io/app-port: "80"
    spec:
      containers:
        - name: ordersapi
          image: ordersapi:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
            - containerPort: 81
              protocol: TCP
          envFrom:
            - configMapRef:
                name: ordersapi-cm

---

kind: Service
apiVersion: v1
metadata:
  name: ordersapi-service
  namespace: faces
  labels:
    app: facesapp
    service: ordersapi
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007
      protocol: TCP
      name: http
    - port: 3500
      targetPort: 3500
      nodePort: 30008
      protocol: TCP
      name: dapr-http
    - port: 50001
      targetPort: 50001
      nodePort: 30009
      protocol: TCP
      name: dapr-grpc
  selector:
    service: ordersapi
